
trigger: none

variables:
  - template: ../config/variables/common.yml

pool:
  vmImage: $[ variables.vmImage ]
  
steps:
  - task: AzureCLI@2
    displayName: Create and Configure Self Hosted Agent
    inputs:
      azureSubscription: $(serviceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment sub Create \
          --location canadacentral \
          --subscription c8515022-4cc9-4ed5-a3fe-182e05d732d8 \
          --template-file $(System.DefaultWorkingDirectory)/myvm/vm/main.bicep \
          --parameters \
            sshkey='$(sshkey)'


